### PR TITLE
Adds more counts to /group and /company

### PR DESCRIPTION
**Pull request by caprenter**
..but the numbers don't seem to add up properly
This is a feature request I guess, but needs work

### CODE REVIEW

**Comment by caprenter** [comment]
If you have time @Bjwebb you might be able to make this work properly...

**Comment by Bjwebb** [comment]
@caprenter Can you point me to some examples of where it doesn't add up?

**Comment by Bjwebb** [comment]
The problem seems to be that this is not a distinct count of projects (in the normal english usage of the term). Where a company has multiple stakes to a project, the project is counted for each stake.

**Comment by Bjwebb** [comment]
I think I've figured this out, looks like counts need their own distinct keyword within the count, see https://github.com/NRGI/resourceprojects.org-frontend/commit/7fc43fe0185ab99bca8ea27f91c390eabc87f124

@caprenter Could you check that this is now behaving as you expect?

**Pull request merged**
