### PR TITLE
[#135] Adds a commodity list and a single commodity page

### PR DESCRIPTION
**Pull request by caprenter**
This is missing tests, and any navigation links right now, but it
seems to work ok
visit it at /commodity

### CODE REVIEW

**Comment by Bjwebb** [comment]
The individual commodity page looks broken to me, all I get is this error:
```
Don't know how to declare  =  (Array
(
    [0] => Array
        (
        )

)
' in /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Generator/PHP.php:541
Stack trace:
#0 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Generator/PHP.php(420): Haanga_Generator_PHP->php_generate_stmt(Array)
#1 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Generator/PHP.php(212): Haanga_Generator_PHP->php_generate_expr(Array)
#2 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Generator/PHP.php(140): Haanga_Generator_PHP->php_if(Array)
#3 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Compiler.php(303): Haanga_Generator_PHP->getCode(Array)
#4 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga/Compiler.php(337): Haanga_Compiler->compile('{%include "../....', '/var/www/html/l...', '/var/www/html/l...')
#5 /var/www/html/lodspeakr/lib/Haanga/lib/Haanga.php(388): Haanga_Compiler->compile_file('/var/www/html/l...', false, Array)
#6 /var/www/html/lodspeakr/classes/Utils.php(694): Haanga::Load('html.template', Array)
#7 /var/www/html/lodspeakr/classes/Utils.php(353): Utils::showView(Array, Object(stdClass), '/var/www/html/l...')
#8 /var/www/html/lodspeakr/classes/modules/typeModule.php(110): Utils::processDocument('/var/www/html/l...', Array, Object(stdClass))
#9 /var/www/html/lodspeakr/index.php(90): TypeModule->execute(Array)
#10 {main}
```

**Comment by caprenter** [comment]
I think this change might need a docker restart/rebuild. Let me know if that's an issue or not

**Comment by Bjwebb** [comment]
Still seems to fail for me even with a docker rebuild...

**Comment by Bjwebb** [comment]
Looks good now that you've amended with the fix.

These pages are not linked from anywhere. Is that captured as/in an issue?

**Comment by caprenter** [comment]
Created issue about link here https://github.com/NRGI/resourceprojects.org-frontend/issues/223
Thanks for reminder

**Pull request merged**
