### PR TITLE
[#17] Adds a country line to the project info box

### PR DESCRIPTION
**Pull request by caprenter**
Also adds tests for this project info box
Note the payments query is stiff failing - see pull request 173

### CODE REVIEW

**Comment by Bjwebb** [comment]
@caprenter This still fails when rebased onto the master with that pull request merged.

**Comment by caprenter** [comment]
The conflicts should now be fixed. Rebased on master, and force pushed a change up

**Comment by Bjwebb** [comment]
@caprenter This is still failing on Travis https://travis-ci.org/OpenDataServices/resourceprojects.org-frontend/builds/86586925

**Comment by caprenter** [comment]
D'oh - fixing it up....

**Pull request merged**
