### PR TITLE
[#51] Adds experimental 'showing x to y of z records' to pager

### PR DESCRIPTION
**Pull request by caprenter**
Problem we have here is that I can't seem to add offset to limit
anywhere to actually calculate anything.

Any ideas?

### CODE REVIEW

**Comment by caprenter** [comment]
Additionally, the query can probably be cleaned up (it may not need the else clause).

I want to say e.g.
Showing records 500 to 1000 of 4983

But I'd also quite like to be able to offer page number links - so that also needs calculations.

OR, there may be a better way...

**Comment by Bjwebb** [comment]
Yes, I think the else clause is not needed.

The place to do arithmetic is probably from the PHP controller code. Currently we're doing this in the settings file, as it's the one PHP file we modify: https://github.com/NRGI/resourceprojects.org-frontend/blob/master/settings.inc.php#L17
Add whatever new computed variables you want there.

**Comment by caprenter** [comment]
Although, I also found this pager in the lodspeakr code, but was not sure how to implement it:
https://github.com/alangrafu/lodspeakr/blob/master/lib/Haanga/contrib/meneame_pagination.php

It looks like it might be an out of the box paging solution - @Bjwebb can you see how/if we would use it?

**Comment by Bjwebb** [comment]
I think it's paginating based on slightly different assumptions, and all it's doing is the arithmetic. Therefore I suspect it's simpler for us to do the arithmetic we want ourselves in settings.inc.php.

**Comment by Bjwebb** [comment]
I've fixed the paging as it currently exists. @caprenter could you create a new issue for page number links?

**Pull request merged**
