### PR TITLE
Update payments.query

### PR DESCRIPTION
**Pull request by timgdavies**
Updating to address issue of duplicates when named payee is present.

### CODE REVIEW

**Comment by caprenter** [comment]
Is this the intention of this change? I'm wondering if this is actually: https://github.com/NRGI/resourceprojects.org-frontend/pull/275

after
before

**Comment by davidmihalyi** [comment]
looks good!

**Comment by caprenter** [comment]
ok --good. I think I follow!

The test pages above are based on: http://alpha.resourceprojects.org/company/f93f8db766d47883.html

**Comment by caprenter** [comment]
This should be ready to merge

**Pull request merged**
