### PR TITLE
[#90] This removes licences from the Projects page and main nav

### PR DESCRIPTION
**Pull request by caprenter**

### CODE REVIEW

**Comment by caprenter** [comment]
@Bjwebb before you do this, I have other things to commit - so hang fire!

**Comment by caprenter** [comment]
ok  - ready now

**Comment by Bjwebb** [comment]
Wondering why you've removed the individual license page, but not the license service?

**Comment by Bjwebb** [comment]
For neatness, I would also recommend removing the two commented out license sections at https://github.com/NRGI/resourceprojects.org-frontend/blob/e3a2ace160401170bd6b06fcafa197bc2922bdbe/components/types/local_def__Country/html.template#L36 and https://github.com/NRGI/resourceprojects.org-frontend/blob/e3a2ace160401170bd6b06fcafa197bc2922bdbe/components/types/local_def__Company/html.template#L16

**Comment by caprenter** [comment]
I agree - changes made as suggested

**Pull request merged**
