### PR TITLE
[#214] A number of improvements to a company group page

### PR DESCRIPTION
**Pull request by caprenter**
Adds an info box
Moves companies table to the right
Fixes missing data in payments and projects tables
Adds 'no data available' switch in template
Adds download links to CSVs
Adds tests for most of this

### CODE REVIEW

**Comment by Bjwebb** [comment]
Looks like we have duplicates in the payments table, I'm looking at http://127.0.0.2/group/bp-3067.html

**Comment by caprenter** [comment]
These may be fixed in https://github.com/NRGI/resourceprojects.org-frontend/pull/209

**Comment by Bjwebb** [comment]
#209 doesn't do anything with the company group page, I don't think, which this particular table is on. You might be able to apply the same fixes to this Group query though...

**Comment by caprenter** [comment]
We've discussed and I'm seeing different data locally.

Agreed to merge this and deal with duplicates as a new issue

**Pull request merged**
