### PR TITLE
Updating sources views

### PR DESCRIPTION
**Pull request by timgdavies**
This should:

* Update the sources table (from the top level nav link)
* Update the view of individual sources
* Update the list-sources service

Tested against local copy with Peru data in, but not against the full corpus.

### CODE REVIEW

**Comment by Bjwebb** [comment]
Here's what this looks like with the full data:
http://sources.lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/source

The sources table has "Details" in the Contributor column (I'm guessing a blank cell is missing?).

`list-sources` doesn't seem to display anything for me. e.g. http://sources.lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/list-sources/http/resourceprojects.org/country/PE

**Comment by davidmihalyi** [comment]
Any chance we can link in the contributor info to that table? #contributor+foaf:name	#contributor+foaf:mbox	#contributor+foaf:homepage   
The tricky thing is that is a different standalone sheet right now.
Unfortunately I don`t think there is a direct data link between contributor data and source data, except that they are both in the same file. (but each source data should have one contributor, not multiple as it currently works)

**Comment by timgdavies** [comment]
I suggest we put this for post Mexico. The data model does not link sources
directly to contributors now. I had assumed breaking these into separate
tables was because you didn't want that link.

We can on an individual source page display the list of contributors to the
graph the source is in, but that will need some work on graph queries.

**Comment by timgdavies** [comment]
@bjwebb I've just pushed an update which deals with the first issue, removing the Contributor cell from the header. 

On the second, I'm not sure what is going on here. I have it working at e.g. http://84.45.121.135:8081/list-sources/http/resourceprojects.org/company/7c327cac123d501b 

Will investigate more.

**Comment by davidmihalyi** [comment]
Ok, fine to park linking contributor to source post-Mexico.

**Comment by Bjwebb** [comment]
I've merged this, as I think this work is better than what's currently on the site.

However the list sources page still doesn't work - http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/list-sources/http/resourceprojects.org/country/PE - so I've created a new issue for that - https://github.com/NRGI/resourceprojects.org-frontend/issues/228

I've also split out the discussion about linking sources and contributors https://github.com/NRGI/resourceprojects.org-frontend/issues/227

**Pull request merged**
